os:
  - linux
  - osx

osx_image: xcode12.5

matrix:
  include:
    # Different distros and compilers on amd64
    - os: linux
      dist: jammy
      arch: amd64
      compiler: gcc
    - os: linux
      dist: jammy
      arch: amd64
      compiler: clang
    # Different architectures, gcc only
    - os: linux
      dist: jammy
      arch: arm64
    - os: linux
      dist: jammy
      arch: ppc64le
    - os: linux
      dist: jammy
      arch: s390x
    # Other OS/dists
    - os: linux
      dist: focal
      arch: amd64
    - os: linux
      dist: bionic
      arch: amd64
    - os: osx
  exclude:
    # Doesn't have min cmake version
    - os: linux
      dist: xenial

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libusb-1.0-0-dev
      - libftdi-dev
      - libhidapi-dev
      - libsensors4-dev
  homebrew:
    packages:
      - libftdi
      - hidapi
    # update: true

install:
  # raplcap dependency
  - git clone https://github.com/powercap/raplcap.git
  - cd raplcap
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX=_install ..
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_CPU_ARCH" == "amd64" ]]; then cmake --build . --target install; fi
  - cd ../..

script:
  - mkdir _build
  - cd _build
    # Test build with stricter flags
  - export CFLAGS="-D_FORTIFY_SOURCE=2 -fstack-protector -g3 -pedantic -Wall -Wextra -Wbad-function-cast -Wcast-align
      -Wcast-qual -Wdisabled-optimization -Wendif-labels -Wfloat-conversion -Wfloat-equal -Wformat=2 -Wformat-nonliteral
      -Winline -Wmissing-declarations -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wshadow
      -Wsign-conversion -Wstrict-prototypes -Wstack-protector -Wundef -Wwrite-strings
      -Werror"
  - PKG_CONFIG_PATH="../raplcap/_build/_install/lib/pkgconfig" cmake .. -DCMAKE_C_FLAGS="$CFLAGS"
  - cmake .. -DCMAKE_C_FLAGS="$CFLAGS"
  - cmake --build . -j
